config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {  :omniauth_callbacks => "omniauth_callbacks", :passwords => "passwords" }
  resources :images
  resources :offer_apartments
  resources :offer_blackboards
  resources :users
  resources :categories
  resources :request_blackboards
  resources :request_apartments

   root 'offer_apartments#index'

end

app/models/offer_apartment.rb
class OfferApartment < ActiveRecord::Base
  has_many :images
  has_one :user
end

app/controllers/offer_apartments_controller.rb
class OfferApartmentsController < ApplicationController
  before_action :set_offer_apartment, only: [:show, :edit, :update, :destroy]

  # GET /offer_apartments
  # GET /offer_apartments.json
  def index
    @offer_apartments = OfferApartment.all
  end

  # GET /offer_apartments/1
  # GET /offer_apartments/1.json
  def show
  end

  # GET /offer_apartments/new
  def new
    @offer_apartment = OfferApartment.new
  end

  # GET /offer_apartments/1/edit
  def edit
  end

  # POST /offer_apartments
  # POST /offer_apartments.json
  def create
    @offer_apartment = OfferApartment.new(offer_apartment_params)

    respond_to do |format|
      if @offer_apartment.save
        format.html { redirect_to @offer_apartment, notice: 'Offer apartment was successfully created.' }
        format.json { render :show, status: :created, location: @offer_apartment }
      else
        format.html { render :new }
        format.json { render json: @offer_apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offer_apartments/1
  # PATCH/PUT /offer_apartments/1.json
  def update
    respond_to do |format|
      if @offer_apartment.update(offer_apartment_params)
        format.html { redirect_to @offer_apartment, notice: 'Offer apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer_apartment }
      else
        format.html { render :edit }
        format.json { render json: @offer_apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offer_apartments/1
  # DELETE /offer_apartments/1.json
  def destroy
    @offer_apartment.destroy
    respond_to do |format|
      format.html { redirect_to offer_apartments_url, notice: 'Offer apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer_apartment
      @offer_apartment = OfferApartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_apartment_params
      params.require(:offer_apartment).permit(:title, :description, :totalPrice, :image_id, :street, :city, :zipcode, :user_id, :size, :rent, :additionalCost, :phase, :deposit, :type, :moveIn, :furnished, :internet, :other, :parking, :rooms, :smoking)
    end
end

app/helpers/offer_apartments_helper.rb
module OfferApartmentsHelper
end

app/views/offer_apartments/_form.html.erb
<%= form_for(@offer_apartment) do |f| %>
  <% if @offer_apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer_apartment.errors.count, "error") %> prohibited this offer_apartment from being saved:</h2>

      <ul>
      <% @offer_apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :totalPrice %><br>
    <%= f.text_field :totalPrice %>
  </div>
  <div class="field">
    <%= f.label :image_id %><br>
    <%= f.number_field :image_id %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.number_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :rent %><br>
    <%= f.text_field :rent %>
  </div>
  <div class="field">
    <%= f.label :additionalCost %><br>
    <%= f.text_field :additionalCost %>
  </div>
  <div class="field">
    <%= f.label :phase %><br>
    <%= f.text_field :phase %>
  </div>
  <div class="field">
    <%= f.label :deposit %><br>
    <%= f.text_field :deposit %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :moveIn %><br>
    <%= f.date_select :moveIn %>
  </div>
  <div class="field">
    <%= f.label :furnished %><br>
    <%= f.check_box :furnished %>
  </div>
  <div class="field">
    <%= f.label :internet %><br>
    <%= f.check_box :internet %>
  </div>
  <div class="field">
    <%= f.label :other %><br>
    <%= f.text_field :other %>
  </div>
  <div class="field">
    <%= f.label :parking %><br>
    <%= f.text_field :parking %>
  </div>
  <div class="field">
    <%= f.label :rooms %><br>
    <%= f.number_field :rooms %>
  </div>
  <div class="field">
    <%= f.label :smoking %><br>
    <%= f.check_box :smoking %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offer_apartments/edit.html.erb
<h1>Editing Offer Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer_apartment %> |
<%= link_to 'Back', offer_apartments_path %>

app/views/offer_apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wohnungsangebote</h1>

 <!-- Container für Suche -->
<div class="panel panel-default">
  <div class="panel-body">
<form>
  <div class="form-group">
    <label for="Ort">Ort</label>
    <input type="text" class="form-control" id="Ort" placeholder="Ravensburg">
  </div>
  <div class="form-group">
  <div class="btn-group" data-toggle="buttons">
    <label class="btn btn-primary active">
      <input type="radio" name="Room-Type" id="WG-Zimmer" autocomplete="off" checked>WG-Zimmer
    </label>
    <label class="btn btn-primary">
      <input type="radio" name="Room-Type" id="Wohnung" autocomplete="off">Wohnung
    </label>
  </div>
    </div>
  <div class="form-group">
  <div class="btn-group" data-toggle="buttons">
    <label class="btn btn-primary active">
      <input type="radio" name="Phase" id="A-Phase" autocomplete="off" checked>A-Phase
    </label>
    <label class="btn btn-primary">
      <input type="radio" name="Phase" id="B-Phase" autocomplete="off">B-Phase
    </label>
    <label class="btn btn-primary">
      <input type="radio" name="Phase" id="Alle" autocomplete="off">Alle
    </label>
  </div>
    </div>
  <button type="submit" class="btn btn-lg center-block">Suchen</button>
</form>
  </div>
</div>
<!-- Ende des Suchcontainers -->

<!-- Ausgabe der Tabelle mit Datensätzen -->
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Totalprice</th>
      <th>Image</th>
      <th>City</th>
      <th>Zipcode</th>
      <th>Size</th>
      <th>Phase</th>
      <th>Type</th>

    </tr>
  </thead>

  <tbody>
    <% @offer_apartments.each do |offer_apartment| %>
      <tr>
        <td><%= link_to offer_apartment.title, offer_apartment %></td>
        <td><%= offer_apartment.totalPrice %></td>
        <td><%= offer_apartment.image_id %></td>
        <td><%= offer_apartment.street %></td>
        <td><%= offer_apartment.city %></td>
        <td><%= offer_apartment.zipcode %></td>
        <td><%= offer_apartment.size %></td>
        <td><%= offer_apartment.phase %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<!-- Ende der Tabellenausgabe -->
<br>

<%= link_to 'New Offer apartment', new_offer_apartment_path %>

app/views/offer_apartments/new.html.erb
<h1>New Offer Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', offer_apartments_path %>

app/views/offer_apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @offer_apartment.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @offer_apartment.description %>
</p>

<p>
  <strong>Totalprice:</strong>
  <%= @offer_apartment.totalPrice %>
</p>

<p>
  <strong>Image:</strong>
  <%= @offer_apartment.image_id %>
</p>

<p>
  <strong>Street:</strong>
  <%= @offer_apartment.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @offer_apartment.city %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @offer_apartment.zipcode %>
</p>

<p>
  <strong>User:</strong>
  <%= @offer_apartment.user_id %>
</p>

<p>
  <strong>Size:</strong>
  <%= @offer_apartment.size %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @offer_apartment.rent %>
</p>

<p>
  <strong>Additionalcost:</strong>
  <%= @offer_apartment.additionalCost %>
</p>

<p>
  <strong>Phase:</strong>
  <%= @offer_apartment.phase %>
</p>

<p>
  <strong>Deposit:</strong>
  <%= @offer_apartment.deposit %>
</p>

<p>
  <strong>Type:</strong>
  <%= @offer_apartment.type %>
</p>

<p>
  <strong>Movein:</strong>
  <%= @offer_apartment.moveIn %>
</p>

<p>
  <strong>Furnished:</strong>
  <%= @offer_apartment.furnished %>
</p>

<p>
  <strong>Internet:</strong>
  <%= @offer_apartment.internet %>
</p>

<p>
  <strong>Other:</strong>
  <%= @offer_apartment.other %>
</p>

<p>
  <strong>Parking:</strong>
  <%= @offer_apartment.parking %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @offer_apartment.rooms %>
</p>

<p>
  <strong>Smoking:</strong>
  <%= @offer_apartment.smoking %>
</p>

<%= link_to 'Edit', edit_offer_apartment_path(@offer_apartment) %> |
<%= link_to 'Back', offer_apartments_path %>