config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {  :omniauth_callbacks => "omniauth_callbacks", :passwords => "passwords" }
  resources :images
  resources :offer_apartments
  resources :offer_blackboards
  resources :users
  resources :categories
  resources :request_blackboards
  resources :request_apartments

   root 'offer_apartments#index'

end

app/models/request_apartment.rb
class RequestApartment < ActiveRecord::Base
  has_one :user
end

app/controllers/request_apartments_controller.rb
class RequestApartmentsController < ApplicationController
  before_action :set_request_apartment, only: [:show, :edit, :update, :destroy]

  # GET /request_apartments
  # GET /request_apartments.json
  def index
    @request_apartments = RequestApartment.all
  end

  # GET /request_apartments/1
  # GET /request_apartments/1.json
  def show
  end

  # GET /request_apartments/new
  def new
    @request_apartment = RequestApartment.new
  end

  # GET /request_apartments/1/edit
  def edit
  end

  # POST /request_apartments
  # POST /request_apartments.json
  def create
    @request_apartment = RequestApartment.new(request_apartment_params)

    respond_to do |format|
      if @request_apartment.save
        format.html { redirect_to @request_apartment, notice: 'Request apartment was successfully created.' }
        format.json { render :show, status: :created, location: @request_apartment }
      else
        format.html { render :new }
        format.json { render json: @request_apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_apartments/1
  # PATCH/PUT /request_apartments/1.json
  def update
    respond_to do |format|
      if @request_apartment.update(request_apartment_params)
        format.html { redirect_to @request_apartment, notice: 'Request apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @request_apartment }
      else
        format.html { render :edit }
        format.json { render json: @request_apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_apartments/1
  # DELETE /request_apartments/1.json
  def destroy
    @request_apartment.destroy
    respond_to do |format|
      format.html { redirect_to request_apartments_url, notice: 'Request apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_apartment
      @request_apartment = RequestApartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_apartment_params
      params.require(:request_apartment).permit(:title, :description, :totalPrice, :user_id, :furnished, :type, :size, :phase, :city, :zipcode)
    end
end

app/helpers/request_apartments_helper.rb
module RequestApartmentsHelper
end

app/views/request_apartments/_form.html.erb
<%= form_for(@request_apartment) do |f| %>
  <% if @request_apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request_apartment.errors.count, "error") %> prohibited this request_apartment from being saved:</h2>

      <ul>
      <% @request_apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :totalPrice %><br>
    <%= f.text_field :totalPrice %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :furnished %><br>
    <%= f.check_box :furnished %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :phase %><br>
    <%= f.text_field :phase %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.number_field :zipcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/request_apartments/edit.html.erb
<h1>Editing Request Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @request_apartment %> |
<%= link_to 'Back', request_apartments_path %>

app/views/request_apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Request Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Totalprice</th>
      <th>User</th>
      <th>Furnished</th>
      <th>Type</th>
      <th>Size</th>
      <th>Phase</th>
      <th>City</th>
      <th>Zipcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @request_apartments.each do |request_apartment| %>
      <tr>
        <td><%= request_apartment.title %></td>
        <td><%= request_apartment.description %></td>
        <td><%= request_apartment.totalPrice %></td>
        <td><%= request_apartment.user_id %></td>
        <td><%= request_apartment.furnished %></td>
        <td><%= request_apartment.type %></td>
        <td><%= request_apartment.size %></td>
        <td><%= request_apartment.phase %></td>
        <td><%= request_apartment.city %></td>
        <td><%= request_apartment.zipcode %></td>
        <td><%= link_to 'Show', request_apartment %></td>
        <td><%= link_to 'Edit', edit_request_apartment_path(request_apartment) %></td>
        <td><%= link_to 'Destroy', request_apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request apartment', new_request_apartment_path %>

app/views/request_apartments/new.html.erb
<h1>New Request Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', request_apartments_path %>

app/views/request_apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @request_apartment.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @request_apartment.description %>
</p>

<p>
  <strong>Totalprice:</strong>
  <%= @request_apartment.totalPrice %>
</p>

<p>
  <strong>User:</strong>
  <%= @request_apartment.user_id %>
</p>

<p>
  <strong>Furnished:</strong>
  <%= @request_apartment.furnished %>
</p>

<p>
  <strong>Type:</strong>
  <%= @request_apartment.type %>
</p>

<p>
  <strong>Size:</strong>
  <%= @request_apartment.size %>
</p>

<p>
  <strong>Phase:</strong>
  <%= @request_apartment.phase %>
</p>

<p>
  <strong>City:</strong>
  <%= @request_apartment.city %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @request_apartment.zipcode %>
</p>

<%= link_to 'Edit', edit_request_apartment_path(@request_apartment) %> |
<%= link_to 'Back', request_apartments_path %>