config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {  :omniauth_callbacks => "omniauth_callbacks", :passwords => "passwords" }
  resources :images
  resources :offer_apartments
  resources :offer_blackboards
  resources :users
  resources :categories
  resources :request_blackboards
  resources :request_apartments

   root 'offer_apartments#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :request_blackboards
  has_many :offer_blackboards
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/offer_apartment.rb
class OfferApartment < ActiveRecord::Base
  has_many :images
  has_one :user
end

app/models/offer_blackboard.rb
class OfferBlackboard < ActiveRecord::Base
  has_many :images
  has_one :user
  has_one :category
end

app/models/request_apartment.rb
class RequestApartment < ActiveRecord::Base
  has_one :user
end

app/models/request_blackboard.rb
class RequestBlackboard < ActiveRecord::Base
  has_one :user
  has_one :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  has_many :offer_apartments
  has_many :offer_blackboards
  has_many :request_apartments
  has_many :request_blackboards

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_mage, only: [:show, :edit, :update, :destroy]

  # GET /Images
  # GET /Images.json
  def index
    @images = Image.all
  end

  # GET /Images/1
  # GET /Images/1.json
  def show
  end

  # GET /Images/new
  def new
    @image = Image.new
  end

  # GET /Images/1/edit
  def edit
  end

  # POST /Images
  # POST /Images.json
  def create
    @image = Image.new(mage_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Images/1
  # PATCH/PUT /Images/1.json
  def update
    respond_to do |format|
      if @image.update(mage_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Images/1
  # DELETE /Images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to mages_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mage
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mage_params
      params.require(:image).permit(:title, :path)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:gender, :firstName, :lastName, :email, :password, :userName, :birthdate, :phone, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/offer_apartments_helper.rb
module OfferApartmentsHelper
end

app/helpers/offer_blackboards_helper.rb
module OfferBlackboardsHelper
end

app/helpers/request_apartments_helper.rb
module RequestApartmentsHelper
end

app/helpers/request_blackboards_helper.rb
module RequestBlackboardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StuVApp</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Navbar oben -->
<nav class="navbar navbar-default navbar-static">
  <div class="navbar-header">
    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">DHBW Wohnungsmarkt</a>
  </div>

  <!-- Verschiedene Elemente der Navigationsleiste -->
  <div class="collapse navbar-collapse js-navbar-collapse">
    <ul class="nav navbar-nav">
      <li class="dropdown dropdown-large">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Angebote <b class="caret"></b></a>

        <ul class="dropdown-menu dropdown-menu-large row">
          <li>
            <ul>
              <li> <%=link_to "Wohnungsmarkt", offer_apartments_path %></li>
              <li> <%=link_to "Schwarzes Brett", offer_blackboards_path %></li>
            </ul>
          </li>
        </ul>

      </li>
      <li class="dropdown dropdown-large">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gesuche <b class="caret"></b></a>

        <ul class="dropdown-menu dropdown-menu-large row">
          <li>
            <ul>
              <li> <%=link_to "Wohnungsmarkt", request_apartments_path %></li>
              <li> <%=link_to "Schwarzes Brett", request_blackboards_path %></li>
            </ul>
          </li>
        </ul>

      </li>
      <li>
        <a href="#">Impressum</a>

      </li>
    </ul>
    <!-- Login Rechts in Navbar -->
    <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li class="dropdown dropdown-large">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%=current_user.email %> <b class="caret"></b></a>

            <ul class="dropdown-menu dropdown-menu-large row">
              <li>
                <ul>
                  <li> <%=link_to "Anzeigen Verwalten", request_apartments_path %></li>
                  <li> <%=link_to "Einstellungen", request_blackboards_path %></li>
                  <li> <%=link_to "Abmelden", destroy_user_session_path, {:method => :delete}%></li>
                </ul>
              </li>
            </ul>

          </li>
        <% else %>
          <li>
            <%= link_to 'Anmelden', new_user_session_path %>
        <% end %>
      </li>
      <li></li>
    </ul>
  </div>
</nav>


<div class="container">

  <div class="starter-template">
    <h1>StuvAPP</h1>
    <p class="lead">DHBW StuvAPP Testt</p>
  </div>

  <%= yield %>


</body>
</html>

app/views/mages/_form.html.erb
<%= form_for(@mage) do |f| %>
  <% if @mage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mage.errors.count, "error") %> prohibited this mage from being saved:</h2>

      <ul>
      <% @mage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mages/edit.html.erb
<h1>Editing Mage</h1>

<%= render 'form' %>

<%= link_to 'Show', @mage %> |
<%= link_to 'Back', mages_path %>

app/views/mages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mages.each do |mage| %>
      <tr>
        <td><%= mage.title %></td>
        <td><%= mage.path %></td>
        <td><%= link_to 'Show', mage %></td>
        <td><%= link_to 'Edit', edit_mage_path(mage) %></td>
        <td><%= link_to 'Destroy', mage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mage', new_mage_path %>

app/views/mages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @mage.title %>
</p>

<p>
  <strong>Path:</strong>
  <%= @mage.path %>
</p>

<%= link_to 'Edit', edit_mage_path(@mage) %> |
<%= link_to 'Back', mages_path %>